const f = () =>{

    
    try{
        let a  = 0;
        console.log(program)
        console.log("program ran succes")
        return 
    }
    catch(err){
        console.log("this is an Error")
        console.log(P)
    }
    finally{
        console.log("Finally run")
    }
}

f()

